[project]
name = "better-rvc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imutils>=0.5.4",
    "opencv-python>=4.11.0.86",
    "pyserial>=3.5",
    "rpi-gpio>=0.7.1",
    "serial>=0.0.97",
    "tqdm>=4.67.1",
]
